# Generated by Django 3.0.4 on 2020-04-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50)),
                ('c_name', models.CharField(max_length=50)),
                ('c_id', models.CharField(max_length=50)),
                ('c_type', models.CharField(max_length=50)),
                ('c_intr', models.CharField(max_length=50)),
                ('c_req', models.CharField(max_length=50)),
                ('others', models.CharField(max_length=50)),
                ('e_grade', models.CharField(max_length=50)),
            ],
        ),
    ]
