# Generated by Django 3.0.4 on 2020-04-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('StudentID', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
                ('Grade', models.CharField(max_length=50)),
                ('newer', models.CharField(max_length=50)),
            ],
        ),
    ]
