# Generated by Django 3.0.4 on 2020-04-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=50)),
                ('c_name', models.CharField(max_length=50)),
                ('c_id', models.CharField(max_length=50)),
                ('c_type', models.CharField(max_length=50)),
                ('c_format', models.CharField(max_length=50)),
                ('home', models.CharField(max_length=50)),
                ('exper', models.CharField(max_length=50)),
                ('exam', models.CharField(max_length=50)),
                ('attend', models.CharField(max_length=50)),
                ('c_intr', models.CharField(max_length=50)),
                ('c_req', models.CharField(max_length=50)),
                ('others', models.CharField(max_length=50)),
            ],
        ),
    ]
