# Generated by Django 3.0.4 on 2020-04-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('item', models.CharField(max_length=500)),
                ('c_id', models.CharField(max_length=500)),
            ],
        ),
    ]
